# Generated by Django 5.2.8 on 2025-12-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=40)),
                ('Student_Marks', models.IntegerField()),
            ],
        ),
    ]
